from __future__ import annotations

from .models import RegistryRule


RULES: tuple[RegistryRule, ...] = (
    RegistryRule(
        rule_id="league.fifa_world_cup",
        rule_type="league",
        value="FIFA World Cup",
        aliases=(
            r"\bfifa world cup\b",
            r"\bworld cup\b",
        ),
        confidence=0.94,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.uefa_champions_league",
        rule_type="league",
        value="UEFA Champions League",
        aliases=(
            r"\buefa champions league\b",
            r"\bchampions league\b",
            r"\bucl\b",
        ),
        confidence=0.95,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.uefa_europa_league",
        rule_type="league",
        value="UEFA Europa League",
        aliases=(
            r"\buefa europa league\b",
            r"\beuropa league\b",
        ),
        confidence=0.95,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.premier_league",
        rule_type="league",
        value="Premier League",
        aliases=(
            r"\bpremier league\b",
            r"\benglish premier league\b",
            r"\bepl\b",
        ),
        confidence=0.95,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.la_liga",
        rule_type="league",
        value="La Liga",
        aliases=(
            r"\bla liga\b",
        ),
        confidence=0.96,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.serie_a",
        rule_type="league",
        value="Serie A",
        aliases=(
            r"\bserie a\b",
        ),
        confidence=0.96,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.bundesliga",
        rule_type="league",
        value="Bundesliga",
        aliases=(
            r"\bbundesliga\b",
        ),
        confidence=0.96,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.ligue_1",
        rule_type="league",
        value="Ligue 1",
        aliases=(
            r"\bligue 1\b",
        ),
        confidence=0.96,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.mls",
        rule_type="league",
        value="MLS",
        aliases=(
            r"\bmls\b",
            r"\bmajor league soccer\b",
        ),
        confidence=0.95,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="league.nba",
        rule_type="league",
        value="NBA",
        aliases=(
            r"\bnba\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="Basketball",
    ),
    RegistryRule(
        rule_id="league.wnba",
        rule_type="league",
        value="WNBA",
        aliases=(
            r"\bwnba\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="Basketball",
    ),
    RegistryRule(
        rule_id="league.euroleague",
        rule_type="league",
        value="EuroLeague",
        aliases=(
            r"\beuroleague\b",
        ),
        confidence=0.97,
        category="Sports",
        sport="Basketball",
    ),
    RegistryRule(
        rule_id="league.mlb",
        rule_type="league",
        value="MLB",
        aliases=(
            r"\bmlb\b",
            r"\bmajor league baseball\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="Baseball",
    ),
    RegistryRule(
        rule_id="league.nfl",
        rule_type="league",
        value="NFL",
        aliases=(
            r"\bnfl\b",
            r"\bnational football league\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="American Football",
    ),
    RegistryRule(
        rule_id="league.nhl",
        rule_type="league",
        value="NHL",
        aliases=(
            r"\bnhl\b",
            r"\bnational hockey league\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="Ice Hockey",
    ),
    RegistryRule(
        rule_id="league.ufc",
        rule_type="league",
        value="UFC",
        aliases=(
            r"\bufc\b",
            r"\bufc fight night\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="MMA",
    ),
    RegistryRule(
        rule_id="league.bellator",
        rule_type="league",
        value="Bellator",
        aliases=(
            r"\bbellator\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="MMA",
    ),
    RegistryRule(
        rule_id="league.pfl",
        rule_type="league",
        value="PFL",
        aliases=(
            r"\bpfl\b",
            r"\bprofessional fighters league\b",
        ),
        confidence=0.97,
        category="Sports",
        sport="MMA",
    ),
    RegistryRule(
        rule_id="league.atp",
        rule_type="league",
        value="ATP",
        aliases=(
            r"\batp\b",
        ),
        confidence=0.97,
        category="Sports",
        sport="Tennis",
    ),
    RegistryRule(
        rule_id="league.wta",
        rule_type="league",
        value="WTA",
        aliases=(
            r"\bwta\b",
        ),
        confidence=0.97,
        category="Sports",
        sport="Tennis",
    ),
    RegistryRule(
        rule_id="league.pga_tour",
        rule_type="league",
        value="PGA Tour",
        aliases=(
            r"\bpga tour\b",
            r"\bpga\b",
        ),
        confidence=0.95,
        category="Sports",
        sport="Golf",
    ),
    RegistryRule(
        rule_id="league.formula_1",
        rule_type="league",
        value="Formula 1",
        aliases=(
            r"\bformula 1\b",
            r"\bf1\b",
        ),
        confidence=0.97,
        category="Sports",
        sport="Motorsport",
    ),
    RegistryRule(
        rule_id="league.nascar",
        rule_type="league",
        value="NASCAR",
        aliases=(
            r"\bnascar\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="Motorsport",
    ),
    RegistryRule(
        rule_id="league.ipl",
        rule_type="league",
        value="IPL",
        aliases=(
            r"\bipl\b",
            r"\bindian premier league\b",
        ),
        confidence=0.97,
        category="Sports",
        sport="Cricket",
    ),
)
