from __future__ import annotations

from .models import RegistryRule


RULES: tuple[RegistryRule, ...] = (
    RegistryRule(
        rule_id="market_type.moneyline",
        rule_type="market_type",
        value="Moneyline",
        aliases=(
            r"\bmoneyline\b",
            r"\bmoney line\b",
            r"\bmatch winner\b",
            r"\bgame winner\b",
        ),
        confidence=0.96,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.spread",
        rule_type="market_type",
        value="Spread",
        aliases=(
            r"\bspread\b",
            r"\bpoint spread\b",
            r"\bhandicap\b",
            r"\b(?:[+-]\d+(?:\.\d+)?)\s+spread\b",
        ),
        confidence=0.96,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.total",
        rule_type="market_type",
        value="Total",
        aliases=(
            r"\bgame total\b",
            r"\bmatch total\b",
            r"\btotal goals\b",
            r"\btotal points\b",
            r"\btotal runs\b",
            r"\bover\/under\b",
            r"\bover under\b",
            r"\b(?:over|under)\s+\d+(?:\.\d+)?\s+"
            r"(?:goals|points|runs|games|sets|rounds)\b",
        ),
        confidence=0.96,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.team_total",
        rule_type="market_type",
        value="Team Total",
        aliases=(
            r"\bteam total\b",
            r"\bteam goals total\b",
            r"\bteam points total\b",
            r"\bteam runs total\b",
        ),
        confidence=0.98,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.player_prop",
        rule_type="market_type",
        value="Player Prop",
        aliases=(
            r"\bplayer prop\b",
            r"\bplayer props\b",
            r"\bplayer total\b",
            r"\bplayer performance\b",
            r"\bplayer statistics?\b",
        ),
        confidence=0.97,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.both_teams_to_score",
        rule_type="market_type",
        value="Both Teams to Score",
        aliases=(
            r"\bboth teams to score\b",
            r"\bbtts\b",
            r"\bboth teams score\b",
        ),
        confidence=0.99,
        category="Sports",
        sport="Soccer",
    ),
    RegistryRule(
        rule_id="market_type.exact_score",
        rule_type="market_type",
        value="Exact Score",
        aliases=(
            r"\bexact score\b",
            r"\bcorrect score\b",
            r"\bfinal score exactly\b",
        ),
        confidence=0.98,
        category="Sports",
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.to_qualify",
        rule_type="market_type",
        value="To Qualify",
        aliases=(
            r"\bto qualify\b",
            r"\bwill qualify\b",
            r"\badvance to the next round\b",
            r"\bto advance\b",
        ),
        confidence=0.97,
        category="Sports",
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.tournament_winner",
        rule_type="market_type",
        value="Tournament Winner",
        aliases=(
            r"\btournament winner\b",
            r"\bwin the tournament\b",
            r"\bwin the world cup\b",
            r"\bworld cup winner\b",
            r"\bchampionship winner\b",
        ),
        confidence=0.96,
        category="Sports",
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.season_winner",
        rule_type="market_type",
        value="Season Winner",
        aliases=(
            r"\bseason winner\b",
            r"\bwin the league\b",
            r"\bleague winner\b",
            r"\bwin the championship\b",
            r"\bregular season winner\b",
        ),
        confidence=0.96,
        category="Sports",
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.election_winner",
        rule_type="market_type",
        value="Election Winner",
        aliases=(
            r"\belection winner\b",
            r"\bwin the election\b",
            r"\bpresidential election winner\b",
            r"\bwin the presidency\b",
            r"\belected president\b",
        ),
        confidence=0.97,
        category="Politics",
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.award_winner",
        rule_type="market_type",
        value="Award Winner",
        aliases=(
            r"\baward winner\b",
            r"\bwin the award\b",
            r"\bmost valuable player\b",
            r"\bwin mvp\b",
            r"\bwin the oscar\b",
            r"\bwin the grammy\b",
        ),
        confidence=0.96,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.binary_yes_no",
        rule_type="market_type",
        value="Yes/No Binary",
        aliases=(
            r"\byes\/no\b",
            r"\byes or no\b",
            r"\bbinary market\b",
            r"\bbinary outcome\b",
            r"\bresolve(?:s|d)?\s+(?:yes|no)\b",
        ),
        confidence=0.95,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.threshold",
        rule_type="market_type",
        value="Above/Below Threshold",
        aliases=(
            r"\babove or below\b",
            r"\babove\/below\b",
            r"\bthreshold market\b",
            r"\bexceed the threshold\b",
            r"\breach the threshold\b",
            r"\bat least \$?\d+(?:,\d{3})*(?:\.\d+)?\b",
        ),
        confidence=0.93,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.price_target",
        rule_type="market_type",
        value="Price Target",
        aliases=(
            r"\bprice target\b",
            r"\breach \$?\d+(?:,\d{3})*(?:\.\d+)?\b",
            r"\bhit \$?\d+(?:,\d{3})*(?:\.\d+)?\b",
            r"\breach a price of\b",
            r"\btrade above \$?\d+(?:,\d{3})*(?:\.\d+)?\b",
            r"\btrade below \$?\d+(?:,\d{3})*(?:\.\d+)?\b",
        ),
        confidence=0.95,
        category="Finance",
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.range",
        rule_type="market_type",
        value="Range",
        aliases=(
            r"\brange market\b",
            r"\bbetween \$?\d+(?:,\d{3})*(?:\.\d+)? "
            r"and \$?\d+(?:,\d{3})*(?:\.\d+)?\b",
            r"\bwithin the range\b",
            r"\bprice range\b",
            r"\bpercentage range\b",
        ),
        confidence=0.94,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.resolution_event",
        rule_type="market_type",
        value="Resolution Event",
        aliases=(
            r"\bresolution event\b",
            r"\bmarket resolution\b",
            r"\bresolve based on\b",
            r"\bwill be resolved\b",
            r"\bresolution criteria\b",
        ),
        confidence=0.95,
        category=None,
        sport=None,
    ),
    RegistryRule(
        rule_id="market_type.method_of_victory",
        rule_type="market_type",
        value="Method of Victory",
        aliases=(
            r"\bmethod of victory\b",
            r"\bwin by knockout\b",
            r"\bwin by ko\b",
            r"\bwin by tko\b",
            r"\bwin by submission\b",
            r"\bwin by decision\b",
        ),
        confidence=0.98,
        category="Sports",
        sport="MMA",
    ),
    RegistryRule(
        rule_id="market_type.winning_margin",
        rule_type="market_type",
        value="Winning Margin",
        aliases=(
            r"\bwinning margin\b",
            r"\bmargin of victory\b",
            r"\bwin by \d+(?:\.\d+)? or more\b",
            r"\bwin by between \d+ and \d+\b",
        ),
        confidence=0.96,
        category="Sports",
        sport=None,
    ),
)
