"""Minimal example of the Platform Development Kit."""

from tools.pdk import Sprint


def main() -> None:
    (
        Sprint(
            version="1.0.0",
            name="Example Sprint",
        )
        .create_file(
            "generated/example.py",
            "MESSAGE = \"Generated by the PDK\"\n",
        )
        .compile_python("generated")
        .run_tests("tests")
        .git_diff_check()
        .execute()
    )


if __name__ == "__main__":
    main()
