"""Component metadata model used by the PDK."""

from __future__ import annotations

import re
from dataclasses import dataclass, field


class ComponentDefinitionError(ValueError):
    """Raised when component metadata is invalid."""


@dataclass(frozen=True, slots=True)
class ComponentDefinition:
    """Describe one component generated by the PDK."""

    name: str
    component_type: str
    version: str
    class_name: str
    description: str = ""
    imports: tuple[str, ...] = field(default_factory=tuple)
    methods: tuple[str, ...] = field(default_factory=tuple)
    tests: tuple[str, ...] = field(default_factory=tuple)
    dependencies: tuple[str, ...] = field(default_factory=tuple)
    status: str = "experimental"

    NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
    VERSION_PATTERN = re.compile(r"^\d+\.\d+\.\d+$")
    CLASS_PATTERN = re.compile(r"^[A-Z][A-Za-z0-9]*$")

    def __post_init__(self) -> None:
        name = self.name.strip().lower().replace("-", "_")
        component_type = (
            self.component_type
            .strip()
            .lower()
            .replace("-", "_")
        )
        version = self.version.strip()
        class_name = self.class_name.strip()
        description = self.description.strip()
        status = self.status.strip().lower()

        self._validate("name", name, self.NAME_PATTERN)
        self._validate(
            "component_type",
            component_type,
            self.NAME_PATTERN,
        )
        self._validate(
            "version",
            version,
            self.VERSION_PATTERN,
        )
        self._validate(
            "class_name",
            class_name,
            self.CLASS_PATTERN,
        )

        if not status:
            raise ComponentDefinitionError(
                "status cannot be empty."
            )

        object.__setattr__(self, "name", name)
        object.__setattr__(
            self,
            "component_type",
            component_type,
        )
        object.__setattr__(self, "version", version)
        object.__setattr__(
            self,
            "class_name",
            class_name,
        )
        object.__setattr__(
            self,
            "description",
            description,
        )
        object.__setattr__(self, "status", status)

        for field_name in (
            "imports",
            "methods",
            "tests",
            "dependencies",
        ):
            object.__setattr__(
                self,
                field_name,
                self._normalize_tuple(
                    field_name,
                    getattr(self, field_name),
                ),
            )

    @property
    def sprint_name(self) -> str:
        version = self.version.replace(".", "_")

        return (
            f"{self.component_type}_"
            f"{self.name}_"
            f"{version}"
        )

    def template_values(self) -> dict[str, str]:
        return {
            "module_name": self.name,
            "component_type": self.component_type,
            "version": self.version,
            "class_name": self.class_name,
            "description": self.description,
            "status": self.status,
            "sprint_name": self.sprint_name,
        }

    @staticmethod
    def _validate(
        field_name: str,
        value: object,
        pattern: re.Pattern[str],
    ) -> None:
        if not isinstance(value, str):
            raise TypeError(
                f"{field_name} must be a string."
            )

        if not pattern.fullmatch(value):
            raise ComponentDefinitionError(
                f"Invalid {field_name}: {value!r}"
            )

    @staticmethod
    def _normalize_tuple(
        field_name: str,
        value: object,
    ) -> tuple[str, ...]:
        if not isinstance(value, tuple):
            raise TypeError(
                f"{field_name} must be a tuple."
            )

        normalized = []

        for item in value:
            if not isinstance(item, str):
                raise TypeError(
                    f"{field_name} entries must be strings."
                )

            item = item.strip()

            if not item:
                raise ComponentDefinitionError(
                    f"{field_name} cannot contain "
                    "empty values."
                )

            normalized.append(item)

        return tuple(normalized)